### ISSUE TITLE
Compilation Error: Improper import of class NewtonRoot

### ISSUE THREAD

**Issue by angeloarenas** [JerryleeIsaac/cs131_finals_2016#2]
Compilation Error: cannot find method NewtonRoot(java.lang.String,java.lang.String,double,double,int) used in class demos.Prob1.final_implicit.NewtonRoot and in test.demos.Prob1.final_implicit.EulerImplicitTest

**Comment by jkrayco** [comment]
wala na yung NewtonRoot sa demos.Prob1.final_implicit diba? So fixed na to?

**Comment by angeloarenas** [comment]
Weird issue, fixed by changing
`import louie_buera.*` to `import louie_buera.NewtonRoot;`
