### ISSUE TITLE
Compilation Error: Missing import of RK4Class in RK4ClassTest

### ISSUE THREAD

**Issue by angeloarenas** [JerryleeIsaac/cs131_finals_2016#3]
cannot find symbol
  symbol:   variable RK4Class
  location: class demos.Prob2.RK4ClassTest

**Comment by jkrayco** [comment]
just add this line:

`import lyon_lao.*;`

sinubukan ko to pero ayaw matapos ng demos.Prob2.RK4ClassTest. sure ba kayo na gumagana yung test na to? baka nag-forever loop.

**Comment by GrizelyBear** [comment]
This test was actually working before the RK4 class was moved to lyon_lao...

**Comment by jkrayco** [comment]
can you try putting the RK4Class back to demos.Prob2 and test it again? i actually tried pero ayaw rin matapos. would you like to be assigned in this issue?

**Comment by GrizelyBear** [comment]
Yep, ako na bahala sa issue na 'to. :)

**Comment by GrizelyBear** [comment]
It apparently works. It's just so slow.
